version: "3"

volumes:
  pgdata:
  rabbitmq:

services:

  book-store-db:
    image: rudi/book-store-db
    build:
      context: ./BookStore.Database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres   
      - POSTGRES_PASSWORD=masterkey
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  customer-service:
    image: rudi/customer-service
    build:
      context: ./BookStore.CustomerService
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=book-store-db
      - POSTGRES_PORT=5432
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=rahasia
    depends_on:
      - book-store-db
      - rabbitmq
    restart: on-failure    
    
  api-gateway-service:
    image: rudi/api-gateway-service
    build:
      context: ./BookStore.APIGatewayService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports: 
      - 9000:80
    depends_on:
      - customer-service
      
  # docker run -d --name rabbitmq rabbitmq:3-management      
  rabbitmq:
    image: rabbitmq:3-management    
    #container_name: OnlineStoreMQ
    #hostname: OnlineStoreMQ
    #ports:        
    #  - 9001:5671
    #  - 9002:5672
    #  - 9003:15672
  #  environment:
  #    - RABBITMQ_DEFAULT_USER=admin
  #    - RABBITMQ_DEFAULT_PASS=rahasia
  #  volumes:
  #    - rabbitmq:/var/lib/rabbitmq     